/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CursorPosition {
  row: number
  col: number
}

export declare function initTui(): void

export interface KeyboardEvent {
  key: string
  modifiers: Array<string>
}

export declare function moveCursor(direction: string): CursorPosition

export declare function shutdownTui(): void

export declare function startKeyboardListener(callback: ((err: Error | null, arg: KeyboardEvent) => any)): void
