/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function fetchData(id: number): Promise<string>

export declare function greet(name: string): string

export declare function startCounter(callback: ((err: Error | null, arg: number) => any)): void
