/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface BufferInfo {
  index: number
  path?: string
}

export declare function clearLogFd(): void

export declare function clipPos(line: number, ch: number): CursorPosition

export interface CursorPosition {
  line: number
  ch: number
}

export declare function focusEditor(): void

export declare function getBufferCount(): number

export declare function getCurrentBufferIndex(): number

export declare function getCurrentPath(): string | null

export declare function getCursorPos(): CursorPosition

export declare function getLine(line: number): string

export declare function getLineCount(): number

export declare function getLineFirstNonWhitespace(line: number): number

export declare function getRange(startLine: number, startCh: number, endLine: number, endCh: number): string

export declare function getScrollInfo(): ScrollInfo

export declare function getSelection(): string

export declare function getSelections(): Array<string>

export declare function getTerminalWidth(): number

export declare function getVisibleLines(): VisibleLines

export interface HighlightRange {
  startLine: number
  startCh: number
  endLine: number
  endCh: number
}

export declare function indentLine(line: number, indentRight: boolean): void

export declare function indexFromPos(line: number, ch: number): number

export declare function initTui(): void

export interface KeyboardEvent {
  key: string
  modifiers: Array<string>
}

export declare function loadFile(path: string): void

export declare function moveCursor(direction: string): CursorPosition

export declare function nextBuffer(): BufferInfo

export declare function openBuffer(path: string): BufferInfo

export declare function posFromIndex(offset: number): CursorPosition

export declare function prevBuffer(): BufferInfo

export declare function pushUndoStop(): void

export declare function redo(): CursorPosition

export declare function replaceRange(text: string, startLine: number, startCh: number, endLine: number, endCh: number): void

export declare function replaceSelections(texts: Array<string>): void

export declare function saveFile(path: string): void

export interface ScrollInfo {
  top: number
  height: number
  clientHeight: number
}

export declare function scrollTo(y: number): void

export declare function scrollToLine(line: number, position: string): void

export interface Selection {
  anchorLine: number
  anchorCh: number
  headLine: number
  headCh: number
}

export declare function setCurrentPath(path: string): void

export declare function setCursorPos(line: number, ch: number): void

export declare function setHighlights(ranges: Array<HighlightRange>): void

export declare function setLogFd(fd: number): void

export declare function setReplaceMode(active: boolean): void

export declare function setSelection(anchorLine: number, anchorCh: number, headLine: number, headCh: number): void

export declare function setSelections(selections: Array<Selection>): void

export declare function setStatusText(text: string): void

export declare function setVimMode(active: boolean): void

export declare function setVisualMode(mode: string): void

export declare function shutdownTui(): void

export declare function startKeyboardListener(): void

export declare function switchToBuffer(index: number): BufferInfo

export declare function triggerAction(action: string): void

export declare function undo(): CursorPosition

export interface VisibleLines {
  top: number
  bottom: number
}

export declare function waitForKeyboardEvent(): Promise<unknown>
